// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCInQpA5rYjRYFjI784FD4roaBj87nGngo',
    appId: '1:56253229553:web:f7ec731082dd9fcddbfc50',
    messagingSenderId: '56253229553',
    projectId: 'projet-blue-beam-l4',
    authDomain: 'projet-blue-beam-l4.firebaseapp.com',
    storageBucket: 'projet-blue-beam-l4.firebasestorage.app',
    measurementId: 'G-60YXSH6XBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxYEV4DypH76VO_QGTbkZRHcYrUUQcjCM',
    appId: '1:56253229553:android:b0913c6ee0782c88dbfc50',
    messagingSenderId: '56253229553',
    projectId: 'projet-blue-beam-l4',
    storageBucket: 'projet-blue-beam-l4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxlKLS63sOBnFEv6yU2tmIrF58XRqSZGA',
    appId: '1:56253229553:ios:044295b252f1ec53dbfc50',
    messagingSenderId: '56253229553',
    projectId: 'projet-blue-beam-l4',
    storageBucket: 'projet-blue-beam-l4.firebasestorage.app',
    iosBundleId: 'com.example.l4Seance2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxlKLS63sOBnFEv6yU2tmIrF58XRqSZGA',
    appId: '1:56253229553:ios:044295b252f1ec53dbfc50',
    messagingSenderId: '56253229553',
    projectId: 'projet-blue-beam-l4',
    storageBucket: 'projet-blue-beam-l4.firebasestorage.app',
    iosBundleId: 'com.example.l4Seance2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCInQpA5rYjRYFjI784FD4roaBj87nGngo',
    appId: '1:56253229553:web:df97b8af9ac8e2addbfc50',
    messagingSenderId: '56253229553',
    projectId: 'projet-blue-beam-l4',
    authDomain: 'projet-blue-beam-l4.firebaseapp.com',
    storageBucket: 'projet-blue-beam-l4.firebasestorage.app',
    measurementId: 'G-5JVNHF4JE9',
  );
}
