// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc85xqEdo8BcqXPo8C4IU1heOn8Gb7yiM',
    appId: '1:250833211356:web:2f641488dfb437e4ce8919',
    messagingSenderId: '250833211356',
    projectId: 'authentification-e00c7',
    authDomain: 'authentification-e00c7.firebaseapp.com',
    storageBucket: 'authentification-e00c7.firebasestorage.app',
    measurementId: 'G-658EXXSHJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu20Snxf81Cg-oxGxZToXydxeMaYTL3xk',
    appId: '1:250833211356:android:ee8530923b580547ce8919',
    messagingSenderId: '250833211356',
    projectId: 'authentification-e00c7',
    storageBucket: 'authentification-e00c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDthBNHAvxQ0ySRt4e-4JSaV6zA0fs8nrk',
    appId: '1:250833211356:ios:6e025e0d8afddfccce8919',
    messagingSenderId: '250833211356',
    projectId: 'authentification-e00c7',
    storageBucket: 'authentification-e00c7.firebasestorage.app',
    iosClientId: '250833211356-kloh5cv7unusp5lcud1fg43bjecsv4vs.apps.googleusercontent.com',
    iosBundleId: 'com.example.l4Seance2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDthBNHAvxQ0ySRt4e-4JSaV6zA0fs8nrk',
    appId: '1:250833211356:ios:6e025e0d8afddfccce8919',
    messagingSenderId: '250833211356',
    projectId: 'authentification-e00c7',
    storageBucket: 'authentification-e00c7.firebasestorage.app',
    iosClientId: '250833211356-kloh5cv7unusp5lcud1fg43bjecsv4vs.apps.googleusercontent.com',
    iosBundleId: 'com.example.l4Seance2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc85xqEdo8BcqXPo8C4IU1heOn8Gb7yiM',
    appId: '1:250833211356:web:309f292513a5787bce8919',
    messagingSenderId: '250833211356',
    projectId: 'authentification-e00c7',
    authDomain: 'authentification-e00c7.firebaseapp.com',
    storageBucket: 'authentification-e00c7.firebasestorage.app',
    measurementId: 'G-8PM2E0D0C2',
  );

}